from __future__ import annotations

import json
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .paths import repo_root

PACKET_SIZE = 20
VERSION = 1
PACKET_ACTIVITY = 0x10
PACKET_GPS = 0x11
PACKET_EXTENDED = 0x12
UNKNOWN_U8 = 0xFF
UNKNOWN_U16 = 0xFFFF
UNKNOWN_S16 = -32768
SERVICE_UUID = "D8185099-1302-4FEB-906F-0AE8D5329ABA"
TELEMETRY_UUID = "734A1ED9-8E4D-4AEB-A5D7-BEABC20643B8"


@dataclass(frozen=True)
class ActivityPacket:
    sequence: int
    timer_state: int
    sport: int
    heart_rate: int
    timer_seconds: int
    distance_decimeters: int
    speed_centimeters_per_second: int


def encode_activity(packet: ActivityPacket) -> bytes:
    return struct.pack(
        "<8BIIHH",
        PACKET_ACTIVITY,
        VERSION,
        packet.sequence & 0xFF,
        packet.timer_state,
        packet.sport,
        UNKNOWN_U8,
        packet.heart_rate,
        UNKNOWN_U8,
        packet.timer_seconds,
        packet.distance_decimeters,
        packet.speed_centimeters_per_second,
        UNKNOWN_U16,
    )


def encode_gps(*, sequence: int, quality: int, latitude_e7: int, longitude_e7: int,
               altitude_decimeters: int, heading_centidegrees: int,
               timer_seconds: int) -> bytes:
    return struct.pack("<4BiihHI", PACKET_GPS, VERSION, sequence & 0xFF, quality,
                       latitude_e7, longitude_e7, altitude_decimeters,
                       heading_centidegrees, timer_seconds)


def encode_extended(*, sequence: int, zone: int, average_hr: int, maximum_hr: int,
                    average_speed: int, maximum_speed: int, ascent: int,
                    calories: int, hour: int, minute: int, second: int) -> bytes:
    return struct.pack("<6B4H4B H", PACKET_EXTENDED, VERSION, sequence & 0xFF, zone,
                       average_hr, maximum_hr, average_speed, maximum_speed, ascent,
                       calories, hour, minute, second, UNKNOWN_U8, UNKNOWN_U16)


def decode(packet: bytes) -> dict[str, Any]:
    if len(packet) != PACKET_SIZE:
        raise ValueError("ORM packets must be exactly 20 bytes")
    if packet[1] != VERSION:
        raise ValueError("unsupported ORM protocol version")
    if packet[0] == PACKET_ACTIVITY:
        values = struct.unpack("<8BIIHH", packet)
        if values[3] > 3:
            raise ValueError("invalid timer state")
        return {"type": "activity", "sequence": values[2], "timer_state": values[3],
                "sport": values[4], "heart_rate": values[6], "timer_seconds": values[8],
                "distance_decimeters": values[9], "speed_centimeters_per_second": values[10]}
    if packet[0] == PACKET_GPS:
        values = struct.unpack("<4BiihHI", packet)
        if not -900000000 <= values[4] <= 900000000 or not -1800000000 <= values[5] <= 1800000000:
            raise ValueError("invalid coordinates")
        return {"type": "gps", "sequence": values[2], "quality": values[3],
                "latitude_e7": values[4], "longitude_e7": values[5],
                "altitude_decimeters": values[6], "heading_centidegrees": values[7],
                "timer_seconds": values[8]}
    if packet[0] == PACKET_EXTENDED:
        values = struct.unpack("<6B4H4B H", packet)
        if values[3] not in {*range(6), UNKNOWN_U8}:
            raise ValueError("invalid heart-rate zone")
        return {"type": "extended", "sequence": values[2], "zone": values[3],
                "average_hr": values[4], "maximum_hr": values[5],
                "average_speed": values[6], "maximum_speed": values[7],
                "ascent": values[8], "calories": values[9], "hour": values[10],
                "minute": values[11], "second": values[12]}
    raise ValueError("unknown ORM packet type")


def schema() -> dict[str, Any]:
    return json.loads(
        (repo_root() / "development" / "protocol" / "orm-protocol.json").read_text()
    )


def generated_constants() -> dict[Path, str]:
    root = repo_root() / "development" / "protocol" / "generated"
    c_header = f"""#pragma once
#define ORM_PROTOCOL_VERSION {VERSION}
#define ORM_BLE_DEVICE_NAME \"ORM\"
#define ORM_SERVICE_UUID \"{SERVICE_UUID}\"
#define ORM_TELEMETRY_UUID \"{TELEMETRY_UUID}\"
#define ORM_PACKET_ACTIVITY 0x10
#define ORM_PACKET_GPS 0x11
#define ORM_PACKET_EXTENDED 0x12
"""
    monkey = f"""module OrmGeneratedProtocol {{
    const VERSION = {VERSION};
    const DEVICE_NAME = \"ORM\";
    const SERVICE_UUID = \"{SERVICE_UUID}\";
    const TELEMETRY_UUID = \"{TELEMETRY_UUID}\";
    const PACKET_ACTIVITY = 0x10;
    const PACKET_GPS = 0x11;
    const PACKET_EXTENDED = 0x12;
}}
"""
    python = f"""# Generated by orm protocol generate. Do not edit.
VERSION = {VERSION}
DEVICE_NAME = \"ORM\"
SERVICE_UUID = \"{SERVICE_UUID}\"
TELEMETRY_UUID = \"{TELEMETRY_UUID}\"
PACKET_ACTIVITY = 0x10
PACKET_GPS = 0x11
PACKET_EXTENDED = 0x12
"""
    return {root / "orm_protocol.h": c_header, root / "OrmGeneratedProtocol.mc": monkey,
            root / "orm_protocol.py": python}


def generate() -> None:
    for path, content in generated_constants().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def check_generated() -> list[str]:
    errors: list[str] = []
    spec = schema()
    transport = spec["transport"]
    if spec["version"] != VERSION or transport["packet_size"] != PACKET_SIZE:
        errors.append("Python protocol constants disagree with schema")
    if transport["service_uuid"] != SERVICE_UUID or transport["telemetry_characteristic_uuid"] != TELEMETRY_UUID:
        errors.append("Python BLE UUIDs disagree with schema")
    for path, expected in generated_constants().items():
        if not path.exists() or path.read_text() != expected:
            errors.append(f"stale generated protocol file: {path.relative_to(repo_root())}")
    consumers = {
        repo_root() / "firmware/esp32/OpenRideMirror/OpenRideMirror.ino":
            (SERVICE_UUID, TELEMETRY_UUID, "PROTOCOL_VERSION = 1"),
        repo_root() / "garmin/OpenRideMirror/source/OrmBleTransport.mc":
            (SERVICE_UUID, TELEMETRY_UUID, 'DEVICE_NAME = "ORM"'),
        repo_root() / "garmin/OpenRideMirror/source/OrmProtocol.mc":
            ("PROTOCOL_VERSION = 1",),
    }
    for path, markers in consumers.items():
        text = path.read_text() if path.exists() else ""
        for marker in markers:
            if marker not in text:
                errors.append(f"protocol consumer is out of sync: {path.relative_to(repo_root())} ({marker})")
    return errors
